services:
  resource-management-api:
    container_name: resource-management-api
    image: resource-management-api
    build:
      context: ./Api
      dockerfile: Dockerfile
    ports:
      - "5054:80"
    depends_on:
      - resource-management-db

  resource-management-db:
    container_name: resource-management-db
    image: resource-management-db
    build:
      context: ./Database
      dockerfile: Dockerfile
    ports:
      - 5434:1433
    environment:
      - SA_PASSWORD=Yukon900
      - ACCEPT_EULA=Y

networks:
  default:
    external: true
    name: karma_default